### PR TITLE
Update maintainers list

### PR DESCRIPTION
**Pull request by ryjones**
Alpha sort, remove Gerrit pointer

### CODE REVIEW

**Comment by ryjones** [comment]
> why isn't there an approve button...? Why do I have to go into a review menu?

no idea, you should see one

**Comment by ryjones** [comment]
> I realize we link to the Fabric maintainers file and talk about a release manager, both of which don't apply for the EVM. I can remove it in a followup PR if you agree @MHBauer

I can update my PR if you like

**Comment by MHBauer** [comment]
Not terribly concerned with staying or going. I do not know why the wording was present initially.

Probably good to have some link to a project with more people involved.

At this point, I'd say take it out. We can modify it or an update can be pushed.

**Comment by ryjones** [comment]
OK. I removed the CODEOWNERS change and kept the MAINTAINERS change, with the removal of the pointer to the other team

**Pull request merged**
