### PR TITLE
FAB-16727 Fix address case sensitivity

### PR DESCRIPTION
**Pull request by dplumb94**
Addresses can now be matched regardless of case in parsing logs.

Signed-off-by: Darian Plumb <dplumb@bitwise.io>

Thank you for contributing to the `fabric-chaincode-evm` project!
Please look at our [Contributions Docs](../README.md#Contributions) and make
sure you have done the following before submitting:

* [ ] Ran the basic checks: `make basic-checks`
* [ ] Ran the unit tests: `make unit-test`
* [ ] Ran the integration tests: `make integration-test`
* [x] Added the associated JIRA ticket number in the commit message title
* [x] Link to the JIRA Ticket: https://jira.hyperledger.org/browse/FAB-16727

If you do not have a corresponding JIRA ticket, please open one in the [Fabric
JIRA](https://jira.hyperledger.org/projects/FAB/issues) and add
`fabric-chaincode-evm` as the component. In the JIRA ticket, include use
cases, design and other information useful to understanding why you are making
this pull request.

If you have any questions please feel free to ask in the #fabric-evm channel
on the [Hyperledger Chat](https://chat.hyperledger.org/channel/fabric-evm).

Thanks again for your contribution!

### CODE REVIEW

**Comment by swetharepakula** [comment]
This PR was done as part of an exercise in Hyperledger Maintainer Summit. Tests will be added afterwards

**Comment by MHBauer** [comment]
changeID is purely a gerrit thing. with switch to github PRs, there is no need for changeID.

We should all probably take the gerrit pre-commit hooks out of our repos.

**Comment by swetharepakula** [comment]
I will take over this change. Spoke with @dplumb94 offline to confirm.

**Comment by swetharepakula** [comment]
Closing in favor of #18

**Pull request closed without merging**
